<?php
get_header();
$water_challenges = ['Climate change', 'Recurring droughts', 'Population growth', 'Industrial demand', 'Groundwater depletion', 'Aging infrastructure'];
$countries = ['Spain', 'Italy', 'France', 'Germany', 'Netherlands', 'Belgium', 'Portugal', 'Greece', 'Poland', 'Romania', 'Czech Republic'];
$solutions = [
    ['Desalination', 'Solves regional freshwater shortages where conventional sources are constrained.', 'Coastal regions, islands, emergency supply, industrial facilities.', 'Municipalities, utilities, industry, tourism infrastructure.', 'New water capacity with scalable system design.'],
    ['Water Purification', 'Removes contaminants and improves water quality for demanding applications.', 'Groundwater, surface water, technical water and difficult streams.', 'Utilities, municipalities, agriculture, industrial operators.', 'Higher-quality output and safer reuse pathways.'],
    ['Water Reuse', 'Reduces dependence on freshwater withdrawals by recovering usable water.', 'Municipal reuse, process water, irrigation, industrial loops.', 'Cities, utilities, manufacturing, agriculture.', 'Lower water demand and stronger circular-water performance.'],
    ['Brine Conversion', 'Transforms concentrate streams from a disposal problem into recoverable outputs.', 'RO concentrate, desalination brine, salt recovery and ZLD programs.', 'Desalination plants, utilities, industrial sites.', 'Resource recovery and reduced liquid discharge.'],
    ['Industrial Water Recovery', 'Helps facilities recover water from complex process and waste streams.', 'Cooling, washing, mining, energy, manufacturing and wastewater loops.', 'Industrial operators, EPC firms, energy sector.', 'Reduced water cost, lower discharge pressure and improved resilience.'],
    ['Water Production Systems', 'Supports distributed drinking-water production where infrastructure is limited.', 'Remote communities, emergency response, modular supply and bottling.', 'Governments, municipalities, humanitarian programs.', 'Reliable water availability with modular deployment options.'],
];
$audiences = ['Municipalities', 'Water Utilities', 'Industry', 'Agriculture', 'Energy Sector', 'Remote Communities'];
$why = ['Innovative Technologies', 'Sustainable Solutions', 'Scalable Systems', 'Resource Recovery', 'Lower Operating Costs', 'Environmental Responsibility'];
$use_cases = ['Drought resilience', 'Emergency drinking water supply', 'Industrial water reuse', 'Desalination projects', 'Water recovery systems', 'Circular water economy'];
?>
<section class="eu-hero">
    <div class="eu-map" aria-hidden="true"></div>
    <div class="shell eu-hero__grid">
        <div>
            <p class="eyebrow">Europe water resilience</p>
            <h1>Europe’s Water Future Requires New Solutions.</h1>
            <p class="lede">From droughts and falling river levels to growing industrial and municipal demand, water scarcity is becoming one of Europe’s greatest strategic challenges.</p>
            <p>ARBOK develops advanced technologies for desalination, water purification, water reuse, brine conversion, industrial water recovery and sustainable water production.</p>
            <div class="button-row"><a class="button" href="#europe-water-contact">Request Consultation</a><a class="button button-ghost" href="<?php echo esc_url(get_post_type_archive_link('technology')); ?>">Explore Technologies</a></div>
        </div>
        <aside class="eu-hero-card"><span>Strategic challenge</span><strong>Water scarcity is becoming an infrastructure, industry and security issue across Europe.</strong><ul><li>Desalination</li><li>Water reuse</li><li>Industrial recovery</li><li>Zero Waste Discharge</li></ul></aside>
    </div>
</section>
<section class="section eu-challenge"><div class="shell"><div class="section-heading"><div><p class="eyebrow dark">The European water challenge</p><h2>Water stress is moving from local issue to strategic priority.</h2></div><p class="section-intro-copy">Climate pressure, aging systems and rising demand are increasing the burden on municipalities, utilities and industrial operators.</p></div><div class="eu-stat-grid"><article><strong>11</strong><span>European countries highlighted for increasing water stress</span></article><article><strong>6</strong><span>structural drivers: climate, demand, depletion and infrastructure</span></article><article><strong>24/7</strong><span>need for resilient drinking-water and process-water systems</span></article></div><div class="eu-country-panel"><h3>Countries experiencing increasing water stress</h3><div><?php foreach ($countries as $country) : ?><span><?php echo esc_html($country); ?></span><?php endforeach; ?></div></div><div class="eu-challenge-grid"><?php foreach ($water_challenges as $item) : ?><article><span>•</span><strong><?php echo esc_html($item); ?></strong></article><?php endforeach; ?></div></div></section>
<section class="section eu-solutions"><div class="shell"><div class="section-heading"><div><p class="eyebrow dark">How ARBOK can help</p><h2>Advanced water technologies for resilient systems.</h2></div></div><div class="eu-solution-grid"><?php foreach ($solutions as [$title, $problem, $applications, $industries, $benefits]) : ?><article><h3><?php echo esc_html($title); ?></h3><dl><dt>Problem solved</dt><dd><?php echo esc_html($problem); ?></dd><dt>Applications</dt><dd><?php echo esc_html($applications); ?></dd><dt>Industries</dt><dd><?php echo esc_html($industries); ?></dd><dt>Benefits</dt><dd><?php echo esc_html($benefits); ?></dd></dl></article><?php endforeach; ?></div></div></section>
<section class="section section-soft eu-audiences"><div class="shell"><p class="eyebrow dark">Solutions for</p><h2>Organizations responsible for water security and infrastructure resilience.</h2><div class="eu-pill-grid"><?php foreach ($audiences as $item) : ?><article><span>↗</span><strong><?php echo esc_html($item); ?></strong></article><?php endforeach; ?></div></div></section>
<section class="section eu-why"><div class="shell"><div class="section-heading"><div><p class="eyebrow dark">Why ARBOK</p><h2>Technology aligned with sustainable water resilience.</h2></div></div><div class="eu-why-grid"><?php foreach ($why as $i => $item) : ?><article><span><?php echo esc_html(str_pad((string) $i + 1, 2, '0', STR_PAD_LEFT)); ?></span><strong><?php echo esc_html($item); ?></strong></article><?php endforeach; ?></div></div></section>
<section class="section section-dark eu-use-cases"><div class="shell"><div class="section-heading"><div><p class="eyebrow">Use cases</p><h2>From drought response to circular water economy.</h2></div></div><div class="eu-use-grid"><?php foreach ($use_cases as $item) : ?><article><?php echo esc_html($item); ?></article><?php endforeach; ?></div></div></section>
<section class="section eu-partnership"><div class="shell eu-partnership__grid"><div><p class="eyebrow dark">Partnerships</p><h2>Let’s Build Europe’s Water Resilience Together.</h2><p>ARBOK is seeking partnerships with governments, water utilities, municipalities, engineering companies, industrial operators, investors and research organizations.</p><a class="button button-dark" href="#europe-water-contact">Schedule a Meeting</a></div><div class="eu-partner-list"><span>Governments</span><span>Water Utilities</span><span>Municipalities</span><span>Engineering Companies</span><span>Industrial Operators</span><span>Investors</span><span>Research Organizations</span></div></div></section>
<section id="europe-water-contact" class="section eu-lead-section"><div class="shell contact-grid"><div><p class="eyebrow dark">Request consultation</p><h2>Contact ARBOK about water resilience in Europe.</h2><p>Tell us about your region, facility, project or investment mandate. The ARBOK team will review your request and respond with the relevant next step.</p></div><form class="contact-form eu-lead-form" method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="arbok_contact"><input type="hidden" name="subject" value="Europe Water Resilience consultation"><input type="hidden" name="inquiry_context" value="Europe Water Resilience landing page"><?php wp_nonce_field('arbok_contact', 'arbok_contact_nonce'); ?><?php if (function_exists('arbok_contact_spam_fields')) { arbok_contact_spam_fields(); } ?><label><span>Name</span><input name="name" required></label><label><span>Company</span><input name="organization" required></label><label><span>Country</span><input name="country" required></label><label><span>Email</span><input type="email" name="email" required></label><label><span>Phone</span><input name="phone"></label><label><span>I represent</span><select name="representing" required><option value="">Select</option><option>Government</option><option>Municipality</option><option>Utility</option><option>Industry</option><option>Investor</option><option>Research Organization</option><option>Other</option></select></label><label class="full"><span>Message</span><textarea name="message" required placeholder="Tell us about your water challenge, project or partnership interest."></textarea></label><label class="consent full"><input type="checkbox" name="consent" value="1" required><span>I consent to ARBOK contacting me about this request.</span></label><input class="form-honeypot" name="website" tabindex="-1" autocomplete="off"><div class="full form-footer"><button class="button button-dark" type="submit">Contact ARBOK</button></div></form></div></section>
<section class="section eu-faq"><div class="shell narrow"><p class="eyebrow dark">FAQ</p><h2>Water resilience questions</h2><?php $faqs = ['How can Europe address water scarcity?' => 'Europe can combine demand management, infrastructure modernization, water reuse, desalination, industrial recovery and regional resilience planning.', 'What technologies can improve water resilience?' => 'Water purification, reuse, brine conversion, industrial recovery and modular water production can improve resilience across municipalities and industries.', 'Can desalination help European regions?' => 'Yes. Desalination can support coastal regions, islands, emergency supply and industrial projects when designed with sustainability and recovery in mind.', 'How can industries reduce water consumption?' => 'Industries can recover process water, reuse treated streams, reduce discharge and integrate circular-water systems into operations.', 'What is water reuse?' => 'Water reuse means treating wastewater or process water so it can be safely used again for municipal, agricultural or industrial purposes.', 'How can municipalities improve water security?' => 'Municipalities can diversify supply, reduce losses, modernize treatment, reuse water and prepare emergency drinking-water capacity.']; foreach ($faqs as $q => $a) : ?><details><summary><?php echo esc_html($q); ?></summary><p><?php echo esc_html($a); ?></p></details><?php endforeach; ?></div></section>
<?php get_footer(); ?>
