<?php get_header(); ?>
<section class="page-hero page-hero--compact investor-hero"><div class="shell"><?php arbok_breadcrumbs(); ?><div class="investor-hero-grid"><div><p class="eyebrow">Investor portal</p><h1>Deep-tech exposure across essential infrastructure markets.</h1><p class="lede">A diversified technology pipeline across water, energy, environment and industry.</p><div class="button-row"><a class="button" href="#materials">Request materials</a><a class="button button-ghost" href="<?php echo esc_url(home_url('/contact/?subject=nda')); ?>">Request NDA</a></div></div><div class="investor-proof"><span><strong>21</strong> technologies</span><span><strong>9</strong> sectors</span><span><strong>Global</strong> commercial scope</span></div></div></div></section>
<section class="section"><div class="shell split-heading"><div><p class="eyebrow dark">Investment thesis</p><h2>Multiple markets connected by a common engineering foundation.</h2></div><div><p>ARBOK targets high-cost resource problems where reduced energy demand, waste elimination, useful by-products and modular deployment can create measurable commercial value.</p><ul class="check-list"><li>Defensible IP and process know-how</li><li>Large infrastructure and industrial markets</li><li>Licensing, joint venture and project pathways</li><li>Portfolio exposure across correlated global needs</li></ul></div></div></section>
<section class="section section-soft"><div class="shell"><p class="eyebrow dark">Market areas</p><h2>Designed for essential, capital-intensive systems</h2><div class="grid investor-market-grid"><article><span>01</span><h3>Water security</h3><p>Desalination, brine utilization, purification and water recovery.</p></article><article><span>02</span><h3>Energy systems</h3><p>Hydrogen, heavy water, thermodynamic energy and extreme-environment systems.</p></article><article><span>03</span><h3>Environmental remediation</h3><p>Waste processing, oil-spill recovery and contaminated-water treatment.</p></article><article><span>04</span><h3>Industrial resilience</h3><p>Cooling, transport, crystallization, production and modular infrastructure.</p></article></div></div></section>
<section class="section section-navy"><div class="shell"><div class="section-heading"><div><p class="eyebrow">Commercialization pipeline</p><h2>Progressive technical and commercial de-risking</h2></div></div><div class="pipeline-track"><div><span>01</span><strong>Technical diligence</strong><small>IP, engineering basis and application fit</small></div><div><span>02</span><strong>Pilot partner</strong><small>Site, operating data and demonstration scope</small></div><div><span>03</span><strong>Project structure</strong><small>Capital, strategic partners and commercial model</small></div><div><span>04</span><strong>Licensing / scale</strong><small>Deployment, manufacturing and market expansion</small></div></div></div></section>
<section class="section ip-section"><div class="shell two-column"><div><p class="eyebrow dark">IP and patents</p><h2>Protected engineering is central to the portfolio.</h2></div><div><p>Patent status and detailed technical claims vary by platform. Qualified investors and strategic partners can request structured diligence materials under an appropriate NDA.</p><div class="button-row"><a class="button button-dark" href="<?php echo esc_url(home_url('/contact/?subject=nda')); ?>">Request NDA</a><a class="text-link" href="<?php echo esc_url(home_url('/contact/?subject=ip')); ?>">Discuss IP diligence <span>↗</span></a></div></div></div></section>
<section id="materials" class="section section-soft"><div class="shell"><div class="section-heading"><div><p class="eyebrow dark">Investor materials</p><h2>Request the information relevant to your mandate</h2></div></div><div class="grid material-grid"><article><span>01</span><h3>Corporate overview</h3><p>Portfolio, leadership, commercialization model and strategic priorities.</p><a href="<?php echo esc_url(home_url('/contact/?subject=pitch-deck')); ?>">Request pitch deck <span>↗</span></a></article><article><span>02</span><h3>Technology briefs</h3><p>Application, engineering basis, status and partnership pathway.</p><a href="<?php echo esc_url(home_url('/contact/?subject=technology-briefs')); ?>">Request briefs <span>↗</span></a></article><article><span>03</span><h3>Diligence package</h3><p>Technical and IP materials for qualified discussions under NDA.</p><a href="<?php echo esc_url(home_url('/contact/?subject=nda')); ?>">Request NDA <span>↗</span></a></article></div></div></section>
<section class="section investor-form-section"><div class="shell contact-grid"><div><p class="eyebrow dark">Investor inquiry</p><h2>Start a focused diligence conversation.</h2><p>Tell us your investment mandate, relevant markets and preferred level of technical detail.</p></div><?php get_template_part('template-parts/inquiry-form', null, ['type' => 'Investor inquiry']); ?></div></section>
<?php get_footer(); ?>
