<?php
get_header();
$vision = arbok_media_url('Energy Efficiency', arbok_media_url('Arbok-Vission-00004'));
$mission = arbok_media_url('Arbok-Mission-00003');
$ecosystem = arbok_media_url('EcoSystem_Tab', arbok_media_url('EcoSystem'));
$features = arbok_media_url('ARBOK Tech Features');
?>
<section class="page-hero page-hero--compact about-hero">
    <div class="shell"><?php arbok_breadcrumbs(); ?><div class="inner-hero-grid"><div><p class="eyebrow">About ARBOK</p><h1>Restoring Earth’s natural equilibrium.</h1><p class="lede">The Strategic Research Institute ARBOK develops Zero Waste Discharge technologies for waste processing, water systems, energy generation, climate projects, critical materials and advanced material production.</p></div><?php if ($vision) : ?><div class="inner-hero-media"><img src="<?php echo esc_url($vision); ?>" alt="ARBOK innovation and technology vision"></div><?php endif; ?></div></div>
</section>
<section class="section"><div class="shell intro-grid"><div><p class="eyebrow dark">Institute mission</p><h2>Technology designed to return the planet to balance.</h2></div><div><p>In its natural state, the planet exists in equilibrium: the balance of its elements is neutral, self-sufficient and self-regulating. By extracting fossil resources, burning fuel and generating household, industrial and agricultural waste, humanity disrupts this balance, accelerating ecosystem degradation and climate change.</p><p>The Strategic Research Institute ARBOK holds a unique technology portfolio designed not only to process most categories of human-generated waste — including waterborne, organic, chemical and underground waste streams — but also to generate energy without relying on wind, solar or other conventional renewables, deliver climate projects, extract critical materials and produce new materials with universal properties.</p><p>At the center of this work is ARBOK’s ZERO WASTE DISCHARGE ideology. We believe it should become a global standard for the future: a practical framework for returning value to industrial processes while eliminating destructive waste streams.</p><p>By implementing ARBOK technologies, we seek to restore the balance the planet would preserve without destructive human interference. The restoration of Earth’s natural equilibrium is the mission entrusted to us by God, and we fulfill it through every project we deliver.</p></div></div></section>
<section class="section about-principles"><div class="shell principles-grid"><article><?php if ($mission) : ?><img src="<?php echo esc_url($mission); ?>" alt="ARBOK mission"><?php endif; ?><span>01</span><h3>Mission</h3><p>Restore Earth’s natural equilibrium by applying ARBOK technologies to eliminate destructive waste streams and recover value from human activity.</p></article><article><?php if ($vision) : ?><img src="<?php echo esc_url($vision); ?>" alt="ARBOK vision"><?php endif; ?><span>02</span><h3>Vision</h3><p>Establish ZERO WASTE DISCHARGE as a global technology standard for water, waste, energy, climate and materials systems.</p></article></div></section>
<section class="section ecosystem-section"><div class="shell ecosystem-grid"><div class="ecosystem-media"><?php if ($ecosystem) : ?><img src="<?php echo esc_url($ecosystem); ?>" alt="ARBOK Water Solutions Ecosystem"><?php endif; ?></div><div><p class="eyebrow dark">Integrated technology suite</p><h2>ARBOK Water Solutions Ecosystem</h2><p>ARBOK’s technology suite connects waste processing, water production, energy generation, climate applications, critical-material extraction and advanced materials into a unified Zero Waste Discharge framework.</p><a class="button button-dark" href="<?php echo esc_url(get_post_type_archive_link('technology')); ?>">Explore technologies</a></div></div></section>
<section class="section section-soft"><div class="shell intro-grid"><div><p class="eyebrow dark">Source-stated technology objectives</p><h2>Efficiency, useful outputs and environmental responsibility.</h2><p>These portfolio objectives are preserved from ARBOK source materials and require project-specific technical validation.</p></div><div class="proof-list proof-list--grid"><span>High water recovery</span><span>Potable-water quality target</span><span>Dry technical salt output</span><span>Zero-liquid-discharge objective</span><span>Standalone or RO integration</span><span>Modular application design</span></div></div></section>
<section class="section"><div class="shell two-column"><div><p class="eyebrow dark">Corporate profile</p><h2>STRATEGIC RESEARCH INSTITUTE ARBOK</h2><p>Strategic research institute developing technologies for Zero Waste Discharge, resource recovery and restoration of natural equilibrium.</p></div><div><dl class="corporate-facts"><div><dt>Public contact</dt><dd><a href="mailto:info@arbok.tech">info@arbok.tech</a><br><a href="tel:+19292351625">+1 (929) 235-1625</a></dd></div><div><dt>Technology scope</dt><dd>Water, waste, energy, climate, critical materials and advanced material systems</dd></div><div><dt>Verification status</dt><dd>Registered address, jurisdiction and corporate registration number require confirmation before production publication.</dd></div></dl></div></div></section>
<section class="section contact-cta"><div class="shell contact-cta__inner"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/arbok-logo.png'); ?>" alt=""><div><p class="eyebrow">Explore the portfolio</p><h2>See how ARBOK applies its engineering platform across nine sectors.</h2><div class="button-row"><a class="button" href="<?php echo esc_url(get_post_type_archive_link('sector')); ?>">View sectors</a><a class="button button-ghost" href="<?php echo esc_url(home_url('/contact/')); ?>">Contact ARBOK</a></div></div></div></section>
<?php get_footer(); ?>
